//
// Created by riyan on 9/15/26.
//

#ifndef RESEAU_DE_NEURONES_FROM_SCRATCH_C_ACTIVATIONS_HPP
#define RESEAU_DE_NEURONES_FROM_SCRATCH_C_ACTIVATIONS_HPP

#endif //RESEAU_DE_NEURONES_FROM_SCRATCH_C_ACTIVATIONS_HPP
