//
// Created by riyan on 9/15/26.
//

#ifndef RESEAU_DE_NEURONES_FROM_SCRATCH_C_TRANSITION_HPP
#define RESEAU_DE_NEURONES_FROM_SCRATCH_C_TRANSITION_HPP

#endif //RESEAU_DE_NEURONES_FROM_SCRATCH_C_TRANSITION_HPP
